"use strict";
// import { Validador } from "./validador";
// console.log(Validador.longitudMayor('hola mundo', 3));
// console.log(Validador.soloLetras('hola mundo'));
// console.log(Validador.soloLetras('h0la mund0'));
exports.__esModule = true;
// import { Validador as Val } from "./validador";
// console.log(Val.longitudMayor('hola mundo', 3));
// console.log(Val.soloLetras('hola mundo'));
// console.log(Val.soloLetras('h0la mund0'));
// import * as Validaciones from "./validador";
// console.log(Validaciones.Validador.longitudMayor('hola mundo', 3));
// console.log(Validaciones.Validador.soloLetras('hola mundo'));
// console.log(Validaciones.Validador.soloLetras('h0la mund0'));
// Validaciones.a();
var validador_1 = require("./validador");
console.log(validador_1["default"].longitudMayor('hola mundo', 3));
console.log(validador_1["default"].soloLetras('hola mundo'));
console.log(validador_1["default"].soloLetras('h0la mund0'));
validador_1.a();
